module.exports = {
    types:[
        'bool',
        'bin',
        'oct',
        'num',
        'hex',
        'str',
        'arr',
        'obj',
        'fn',
        'module',
        'super',
        'const'
    ],

    //default "chars"
    /*'': {
        token:'',
        def:'char'
    },*/
    /*"\\": {
        '': {
            token: '\\',
            def: 'str-regex-escape-char'
        },
        'x': fn (primaryHex, secondaryHex) {
            this.hexList = '0123456789abcdef';
            this.boolSet = [0, 0];
            for (this.hex in this.hexList)
                for (this.a in arguments)
                    if (this.a < this.boolSet.length && arguments[this.a] == this.hex)
                        this.boolSet[this.a] = 1;
            if (!!this.boolSet[0] && !!this.boolSet[1]) return {
                token: '\\x' + primaryHex + secondaryHex,
                def: 'char-hex'
            }; else return {
                error: 'TokenError: this current token does not match its parameters, try again!'
            };
        },
        'u': fn (hexA, hexB, hexC, hexD) {
            this.hexList = '0123456789abcdef';
            this.boolSet = [0, 0, 0, 0];
            for (this.hex in this.hexList)
                for (this.a in arguments)
                    if (this.a < this.boolSet && arguments[this.a] == this.hex)
                        this.boolSet[this.a] = 1;
            if (
                !!this.boolSet[0] &&
                !!this.boolSet[1] &&
                !!this.boolSet[2] &&
                !!this.boolSet[3]
            ) return {
                token: '\\u' + hexA + hexB + hexC + hexD,
                def: 'char-unicode'
            }; else return {
                error: 'TokenError: this current token does not match its parameters, try again!'
            };
        },
    },*/

    //whitespace PLEASE FORGIVE ME!!!
    '':{
        token:'',
        def:'please-god-why'
    },
    ' ':{
        token:' ',
        def:{
            symbol:true,
            whitespace:true,
            space:true,
            char:true
        }
    },
    '\n':{
        token:'\n',
        def:{
            symbol:true,
            whitespace:true,
            newline:true,
            char:true
        }
    },
    '\r':{
        token:'\r',
        def:{
            symbol:true,
            whitespace:true,
            carriage:true,
            char:true
        },
        '\n':{
            token:'\r\n',
            def:{
                symbol:true,
                whitespace:true,
                carriage:true,
                newline:true,
                char:true
            },
            pos:true
        }
    },
    '\t':{
        token:'\t',
        def:{
            symbol:true,
            whitespace:true,
            tab:true,
            char:true
        }
    },

    //escape character and its derivatives
    '\\':{
        token:'\\',
        def:{
            symbol:true,
            escape:true
        },
        '\'':{
            token:"\\'",
            def:{
                symbol:true,
                escape:true,
                str:true,
                sgl:true,
                quote:true
            }
        },
        '"':{
            token:'\\"',
            def:{
                symbol:true,
                escape:true,
                str:true,
                dbl:true,
                quote:true
            }
        }
    },

    //enclosure operators
    "(": {
        token:'(',
        def:{
            symbol:true,
            open:true,
            paren:true
        }
    },
    ")": {
        token:')',
        def:{
            symbol:true,
            close:true,
            paren:true
        }
    },
    "[": {
        token:'[',
        def:{
            symbol:true,
            open:true,
            square:true
        }
    },
    "]": {
        token:']',
        def:{
            symbol:true,
            close:true,
            square:true
        }
    },
    "{": {
        token:'{',
        def:{
            symbol:true,
            open:true,
            curly:true
        }
    },
    "}": {
        token:'}',
        def:{
            symbol:true,
            close:true,
            curly:true
        }
    },
    ";": {
        token:';',
        def:{
            symbol:true,
            semicolon:true
        }
    },
    ":": {
        token:':',
        def:{
            symbol:true,
            logic:true,
            colon:true,
            false:true
        }
    },
    '"': {
        token:'"',
        def:{
            symbol:true,
            str:true,
            comp:true,
            dbl:true,
            quote:true
        }
    },
    "'":{
        token:"'",
        def:{
            symbol:true,
            str:true,
            prim:true,
            sgl:true,
            quote:true
        }
    },
    ",": {
        token:',',
        def:{
            symbol:true,
            comma:true
        }
    },
    ".": {
        token:'.',
        def:{
            symbol:true,
            identifier:true,
            assign:true,
            num:true,
            child:true,
            dot:true
        },
        ".": {
            token:"..",
            def:{
                symbol:true,
                num:true,
                range:true
            },
            ".": {
                token:'...',
                def:{
                    symbol:true,
                    assign:true,
                    spread:true,
                    rest:true,
                    arr:true,
                    fn:true,
                    num:true,
                    range:true,
                    exclusive:true
                }
            }
        }
    },
    
    //arithmetic operators prefix
    "+": {
        token:'+',
        def:{
            symbol:true,
            math:true,
            add:true
        },
        "=": {
            token:'+=',
            def:{
                symbol:true,
                math:true,
                self:true,
                add:true
            }
        },
        "+": {
            token:'++',
            def:{
                symbol:true,
                unop:true,
                cycle:true,
                increment:true
            }
        }
    },
    "-": {
        token:'-',
        def:{
            symbol:true,
            math:true,
            subtract:true
        },
        "=": {
            token:'-=',
            def:{
                symbol:true,
                math:true,
                self:true,
                subtract:true
            }
        },
        "-": {
            token:'--',
            def:{
                symbol:true,
                unop:true,
                cycle:true,
                decrement:true
            }
        }
    },
    "*": {
        token:'*',
        def:{
            symbol:true,
            math:true,
            multiply:true
        },
        "=": {
            token:'*=',
            def:{
                symbol:true,
                math:true,
                self:true,
                multiply:true
            }
        },
        "*": {
            token:'**',
            def:{
                symbol:true,
                math:true,
                power:true
            }
        },
        "/": {
            token:'*/',
            def:{
                symbol:true,
                close:true,
                comment:true
            }
        }
    },
    "/": {
        token:'/',
        def:{
            symbol:true,
            math:true,
            divide:true
        },
        "=": {
            token:'/=',
            def:{
                symbol:true,
                math:true,
                self:true,
                divide:true
            }
        },
        "/": {
            token:'//',
            def:{
                symbol:true,
                unop:true,
                line:true,
                comment:true
            }
        },
        "*": {
            token:'/*',
            def:{
                symbol:true,
                open:true,
                comment:true
            }
        }
    },
    "%": {
        token:'%',
        def:{
            symbol:true,
            math:true,
            modulus:true
        },
        "=": {
            token:'%=',
            def:{
                symbol:true,
                math:true,
                self:true,
                modulus:true
            }
        }
    },

    //comparison operators
    // == 
    "=": {
        token:'=',
        def:{
            symbol:true,
            assign:true
        },
        "=": {
            token:'==',
            def:{
                symbol:true,
                logic:true,
                strict:true,
                equal:true
            }
        }
    },
    "!": {
        token:'!',
        def:{
            symbol:true,
            unop:true,
            logic:true,
            not:true
        },
        "=": {
            token:'!=',
            def:{
                symbol:true,
                logic:true,
                not:true,
                equal:true
            }
        },
        "!": {
            token:'!!',
            def:{
                symbol:true,
                unop:true,
                logic:true,
                absolute:true,
                bool:true
            }
        }
    },
    "?": {
        token:'?',
        def:{
            symbol:true,
            logic:true,
            ternary:true,
            true:true
        },
        ".": {
            token:'?.',
            def:{
                symbol:true,
                logic:true,
                optional:true,
                chain:true
            }
        },
        "?":{
            token:'??',
            def:{
                symbol:true,
                logic:true,
                nullish:true
            },
            '?':{
                token:'??=',
                def:{
                    symbol:true,
                    logic:true,
                    assign:true,
                    nullish:true
                }
            }
        }
    },
    ">": {
        token:'>',
        def:{
            symbol:true,
            greater:true,
            than:true
        },
        "=": {
            token:'>=',
            def:{
                symbol:true,
                greater:true,
                than:true,
                equal:true
            }
        },
        ">": {
            token:'>>',
            def:{
                symbol:true,
                bin:true,
                shift:true,
                right:true
            },
            '>':{
                token:'>>>',
                def:{
                    symbol:true,
                    bin:true,
                    unsigned:true,
                    shift:true,
                    right:true
                }
            }
        }
    },
    "<": {
        token:'<',
        def:{
            symbol:true,
            less:true,
            than:true
        },
        "=": {
            token:'<=',
            def:{
                symbol:true,
                less:true,
                than:true,
                equal:true
            }
        },
        "<": {
            token:'<<',
            def:{
                symbol:true,
                bin:true,
                shift:true,
                left:true
            },
            '<': {
                token:'<<<',
                def:{
                    symbol:true,
                    bin:true,
                    unsigned:true,
                    shift:true,
                    left:true
                }
            }
        }
    },
    "&": {
        token:'&',
        def:{
            symbol:true,
            bit:true,
            and:true
        },
        "=": {
            token:'&=',
            def:{
                symbol:true,
                bit:true,
                assign:true,
                and:true
            }
        },
        "&":{
            token:'&&',
            def:{
                symbol:true,
                logic:true,
                and:true
            },
            '=': {
                token: '&&=',
                def:{
                    symbol:true,
                    logic:true,
                    assign:true,
                    true:true,
                    only:true
                }
            }
        }
    },
    "|": {
        token:'|',
        def:{
            symbol:true,
            bit:true,
            or:true
        },
        "=": {
            token:'|=',
            def:{
                symbol:true,
                bit:true,
                assign:true,
                or:true
            }
        },
        "|": {
            token:'||',
            def:{
                symbol:true,
                logic:true,
                or:true
            },
            '=':{
                token:'||=',
                def:{
                    symbol:true,
                    logic:true,
                    assign:true,
                    self:true,
                    or:true
                }
            }
        }
    },
    "^": {
        token:'^',
        def:{
            symbol:true,
            bit:true,
            xor:true
        },
        "=": {
            token:'^=',
            def:{
                symbol:true,
                bit:true,
                assign:true,
                self:true,
                xor:true
            }
        }
    },

    //nums - because WHY NOT
    "0": {
        token:'0',
        def:{
            bin:true,
            oct:true,
            num:true,
            hex:true
        }
    },
    "1": {
        token:'1',
        def:{
            bin:true,
            oct:true,
            num:true,
            hex:true
        }
    },
    "2": {
        token:'2',
        def:{
            oct:true,
            num:true,
            hex:true
        }
    },
    "3": {
        token:'3',
        def:{
            oct:true,
            num:true,
            hex:true
        }
    },
    "4": {
        token:'4',
        def:{
            oct:true,
            num:true,
            hex:true
        }
    },
    "5": {
        token:'5',
        def:{
            oct:true,
            num:true,
            hex:true
        }
    },
    "6": {
        token:'6',
        def:{
            oct:true,
            num:true,
            hex:true
        }
    },
    "7": {
        token:'7',
        def:{
            oct:true,
            num:true,
            hex:true
        }
    },
    "8": {
        token:'8',
        def:{
            num:true,
            hex:true
        }
    },
    "9": {
        token:'9',
        def:{
            num:true,
            hex:true
        }
    },

    //brute force matching: like tokens but for words
    a:{
        token:'a',
        def:{
            letter:true,
            hex:true
        },
        r:{
            token:'ar',
            def:{
                letter:true
            },
            r:{
                token:'arr',
                def:{
                    res:true,
                    type:true,
                    assign:true,
                    arr:true
                }
            }
        }
    },
    A:{
        token:'A',
        def:{
            char:true
        },
        r:{
            token:'Ar',
            def:{
                char:true
            },
            r:{
                token:'Arr',
                def:{
                    res:true,
                    typeof:true,
                    assign:true,
                    arr:true
                },
                '{':{
                    error:'SyntaxError: Malformed token, expected \'\}\' after "Arr"',
                    '}':{
                        token:'Arr{}',
                        def:{
                            res:true,
                            typeof:true,
                            Arr:true,
                            Array:true,
                            Collection:true
                        }
                    }
                },
                '[':{
                    error:'SyntaxError: Malformed token, expected \'\]\' after "Arr"',
                    ']':{
                        token:'Arr[]',
                        def:{
                            res:true,
                            typeof:true,
                            Arr:true,
                            Array:true,
                            List:true
                        }
                    }
                },
                '(':{
                    error:'SyntaxError: Malformed token, expected \'\)\' after "Arr"',
                    ')':{
                        token:'Arr()',
                        def:{
                            res:true,
                            typeof:true,
                            Arr:true,
                            Array:true,
                            Call:true
                        }
                    }
                }
            }
        }
    },
    b:{
        token:'b',
        def:{
            letter:true,
            hex:true
        },
        i:{
            token:'bi',
            def:{
                char:true
            },
            n: {
                token:'bin',
                def:{
                    res:true,
                    type:true,
                    assign:true,
                    num:true,
                    bin:true
                }
            }
        },
        o:{
            token:'bo',
            def:{
                char:true
            },
            o:{
                token:'boo',
                def:{
                    char:true
                },
                l:{
                    token:'bool',
                    def:{
                        res:true,
                        type:true,
                        assign:true,
                        bool:true
                    }
                }
            }
        },
        r:{
            token:'br',
            def:{
                char:true
            },
            e:{
                token:'bre',
                def:{
                    char:true
                },
                a:{
                    token:'brea',
                    def:{
                        char:true
                    },
                    k:{
                        token:'break',
                        def:{
                            res:true,
                            scope:true,
                            loop:true,
                            exit:true,
                            break:true
                        }
                    }
                }
            }
        }
    },
    B:{
        token:'B',
        def:{
            char:true
        },
        i:{
            token:'Bi',
            def:{
                char:true
            },
            n: {
                token:'Bin',
                def:{
                    res:true,
                    typeof:true,
                    Bin:true,
                    Binary:true
                },
                '{':{
                    error:'SyntaxError: Malformed token, expected \'\}\' after "Bin"',
                    '}':{
                        token:'Bin{}',
                        def:{
                            res:true,
                            typeof:true,
                            Bin:true,
                            Binary:true,
                            Collection:true
                        }
                    }
                },
                '[':{
                    error:'SyntaxError: Malformed token, expected \'\]\' after "Bin"',
                    ']':{
                        token:'Bin[]',
                        def:{
                            res:true,
                            typeof:true,
                            Bin:true,
                            Binary:true,
                            List:true
                        }
                    }
                },
                '(':{
                    error:'SyntaxError: Malformed token, expected \')\' after "Bin"',
                    ')':{
                        token:'Bin()',
                        def:{
                            res:true,
                            typeof:true,
                            Bin:true,
                            Binary:true,
                            Call:true
                        }
                    }
                }
            }},
        o:{
            token:'Bo',
            def:{
                char:true
            },
            o:{
                token:'Boo',
                def:{
                    char:true
                },
                l:{
                    token:'Bool',
                    def:{
                        res:true,
                        typeof:true,
                        Bool:true,
                        Boolean:true
                    },
                    '{':{
                        error:'SyntaxError: Malformed token, expected \'\}\' after "Bool"',
                        '}':{
                            token:'Bool{}',
                            def:{
                                res:true,
                                typeof:true,
                                Bool:true,
                                Boolean:true,
                                Collection:true
                            }
                        }
                    },
                    '[':{
                        error:'SyntaxError: Malformed token, expected \'\]\' after "Bool"',
                        ']':{
                            token:'Bool[]',
                            def:{
                                res:true,
                                typeof:true,
                                Bool:true,
                                Boolean:true,
                                List:true
                            }
                        }
                    },
                    '(':{
                        error:'SyntaxError: Malformed token, expected \'\)\' after "Bool"',
                        ')':{
                            token:'Bool()',
                            def:{
                                res:true,
                                typeof:true,
                                Bool:true,
                                Boolean:true,
                                Call:true
                            }
                        }
                    }
                }
            }
        }
    },
    c:{
        token:'c',
        def:{
            letter:true,
            hex:true
        },
        o:{
            token:'co',
            def:{
                char:true
            },
            n:{
                token:"con",
                def:{
                    char:true
                },
                s:{
                    token:'cons',
                    def:{
                        char:true
                    },
                    t:{
                        token:'const',
                        def:{
                            res:true,
                            type:true,
                            assign:true,
                            const:true
                        }
                    }
                },
                t:{
                    token:'cont',
                    def:{
                        char:true
                    },
                    i:{
                        token:'conti',
                        def:{
                            char:true
                        },
                        n:{
                            token:'contin',
                            def:{
                                char:true
                            },
                            u:{
                                token:'continu',
                                def:{
                                    char:true
                                },
                                e: {
                                    token:'continue',
                                    def:{
                                        res:true,
                                        scope:true,
                                        loop:true,
                                        continue:true
                                    }
                                }
                            }
                        }
                    }
                }
            }            
        }
    },
    C:{
        token:'C',
        def:{
            char:true
        },
        o:{
            token:'Co',
            def:{
                char:true
            },
            n:{
                token:"Con",
                def:{
                    char:true
                },
                s:{
                    token:'Cons',
                    def:{
                        char:true
                    },
                    t:{
                        token:'Const',
                        def:{
                            res:true,
                            type:true,
                            const:true
                        },
                        '{':{
                            error:'SyntaxError: Malformed token, expected \'\}\' after "Const"',
                            '}':{
                                token:'Const{}',
                                def:{
                                    res:true,
                                    type:true,
                                    const:true,
                                    collection:true
                                }
                            }
                        },
                        '[':{
                            error:'SyntaxError: Malformed token, expected \'\]\' after "Const"',
                            ']':{
                                token:'Const[]',
                                def:{
                                    res:true,
                                    type:true,
                                    const:true,
                                    list:true
                                }
                            }
                        },
                        '(':{
                            error:'SyntaxError: Malformed token, expected \'\)\' after "Const"',
                            ')':{
                                token:'Const()',
                                def:{
                                    res:true,
                                    type:true,
                                    const:true,
                                    call:true
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    d:{
        token:'d',
        def:{
            letter:true,
            hex:true
        }
    },
    e:{
        token:'e',
        def:{
            letter:true,
            hex:true
        },
        l:{
            token:'el',
            def:{
                char:true
            },
            s:{
                token:'els',
                def:{
                    char:true
                },
                e:{
                    token:'else',
                    def:{
                        res:true,
                        statement:true,
                        scope:true,
                        bool:true,
                        conditional:true,
                        else:true
                    }
                }
            }
        },
        x:{
            token:'ex',
            def:{
                char:true
            },
            p:{
                token:'exp',
                def:{
                    char:true
                },
                o:{
                    token:'expo',
                    def:{
                        char:true
                    },
                    r:{
                        token:'expor',
                        def:{
                            char:true
                        },
                        t:{
                            token:'export',
                            def:{
                                res:true,
                                type:true,
                                module:true,
                                export:true
                            }
                        }
                    }
                }
            }
        }
    },
    f:{
        token:'f',
        def:{
            letter:true,
            hex:true
        },
        a:{
            token:'fa',
            def:{
                char:true
            },
            l:{
                token:'fal',
                def:{
                    char:true
                },
                s:{
                    token:'fals',
                    def:{
                        char:true
                    },
                    e:{
                        token:'false',
                        def:{
                            res:true,
                            value:true,
                            bool:true,
                            false:true
                        }
                    }
                }
            }
        },
        n:{
            token:'fn',
            def:{
                res:true,
                type:true,
                assign:true,
                fn:true
            }
        }
    },
    F:{
        token:'F',
        def:{
            char:true
        },
        n:{
            token:'Fn',
            def:{
                res:true,
                typeof:true,
                Fn:true,
                Function:true
            }
        }
    },
    h:{
        token:'h',
        def:{
            char:true
        },
        e:{
            token:'he',
            def:{
                char:true
            },
            x:{
                token:'hex',
                def:{
                    res:true,
                    type:true,
                    assign:true,
                    num:true,
                    hex:true
                }
            }
        }
    },
    i:{
        token:'i',
        def:{
            char:true
        },
        f:{
            token:'if',
            def:{
                res:true,
                scope:true,
                bool:true,
                condition:true,
                if:true
            }
        },
        n:{
            token:'in',
            def:{
                res:true,
                scope:true,
                in:true
            }
        },
        m:{
            token:'im',
            def:{
                char:true
            },
            p:{
                token:'imp',
                def:{
                    char:true
                },
                o:{
                    token:'impo',
                    def:{
                        char:true
                    },
                    r:{
                        token:'impor',
                        def:{
                            char:true
                        },
                        t:{
                            token:'import',
                            def:{
                                res:true,
                                type:true,
                                module:true,
                                import:true
                            }
                        }
                    }
                }
            }
        }
    },
    n:{
        token:'n',
        def:{
            char:true
        },
        u:{
            token:'nu',
            def:{
                char:true
            },
            m: {
                token:'num',
                def:{
                    res:true,
                    type:true,
                    assign:true,
                    num:true
                }
            }
        }
    },
    o:{
        token:'o',
        def:{
            char:true
        },
        b:{
            token:'ob',
            def:{
                char:true
            },
            j: {
                token:'obj',
                def:{
                    res:true,
                    type:true,
                    assign:true,
                    obj:true
                }
            }
        },
        c:{
            token:'oc',
            def:{
                char:true
            },
            t: {
                token:'oct',
                def:{
                    res:true,
                    type:true,
                    assign:true,
                    num:true,
                    oct:true
                }
            }
        },
        f: {
            token:'of',
            def:{
                res:true,
                scope:true,
                of:true
            }
        }
    },
    O:{
        token:'O',
        def:{
            char:true
        },
        c:{
            token:'Oc',
            def:{
                char:true
            },
            t:{
                token:'Oct',
                def:{
                    res:true,
                    typeof:true,
                    Oct:true,
                    Octal:true
                },
                '{':{
                    error:'SyntaxError: Malformed token, expected \'\}\' after "Oct"',
                    '}':{
                        token:'Oct{}',
                        def:{
                            res:true,
                            typeof:true,
                            Oct:true,
                            Octal:true,
                            Collection:true
                        }
                    }
                },
                '[':{
                    error:'SyntaxError: Malformed token, expected \'\]\' after "Oct"',
                    ']':{
                        token:'Oct[]',
                        def:{
                            res:true,
                            typeof:true,
                            Oct:true,
                            Octal:true,
                            List:true
                        }
                    }
                },
                '(':{
                    error:'SyntaxError: Malformed token, expected \'\)\' after "Oct"',
                    ')':{
                        token:'Oct()',
                        def:{
                            res:true,
                            typeof:true,
                            Oct:true,
                            Octal:true,
                            Call:true
                        }
                    }
                }
            }
        },
        b:{
            token:'Ob',
            def:{
                char:true
            },
            j:{
                token:'Obj',
                def:{
                    res:true,
                    typeof:true,
                    Obj:true,
                    Object:true
                },
                '{':{
                    error:'SyntaxError: Malformed token, expected \'\}\' after "Obj"',
                    '}':{
                        token:'Obj{}',
                        def:{
                            res:true,
                            typeof:true,
                            Obj:true,
                            Object:true,
                            Collection:true
                        }
                    }
                },
                '[':{
                    error:'SyntaxError: Malformed token, expected \'\]\' after "Obj"',
                    ']':{
                        token:'Obj[]',
                        def:{
                            res:true,
                            typeof:true,
                            Obj:true,
                            Object:true,
                            List:true
                        }
                    }
                },
                '(':{
                    error:'SyntaxError: Malformed token, expected \'\)\' after "Obj"',
                    ')':{
                        token:'Obj()',
                        def:{
                            res:true,
                            typeof:true,
                            Obj:true,
                            Object:true,
                            Call:true
                        }
                    }
                }
            }
        }
    },
    r:{
        token:'r',
        def:{
            char:true
        },
        e:{
            token:'re',
            def:{
                char:true
            },
            t:{
                token:'ret',
                def:{
                    char:true
                },
                u:{
                    token:'retu',
                    def:{
                        char:true
                    },
                    r:{
                        token:'retur',
                        def:{
                            char:true
                        },
                        n:{
                            token:'return',
                            def:{
                                res:true,
                                scope:true,
                                exit:true,
                                return:true
                            }
                        }
                    }
                }
            }
        }
    },
    s:{
        token:'s',
        def:{
            char:true
        },
        t:{
            token:'st',
            def:{
                char:true
            },
            r: {
                token:'str',
                def:{
                    res:true,
                    type:true,
                    assign:true,
                    str:true
                }
            }
        }
    },
    S:{
        token:'S',
        def:{
            char:true
        },
        t:{
            token:'St',
            def:{
                char:true
            },
            r:{
                token:'Str',
                def:{
                    res:true,
                    typeof:true,
                    Str:true,
                    String:true
                },
                '{':{
                    error:'SyntaxError: Malformed token, expected \'\}\' after "Str"',
                    '}':{
                        token:'Str{}',
                        def:{
                            res:true,
                            typeof:true,
                            Str:true,
                            String:true,
                            Collection:true
                        }
                    }
                },
                '[':{
                    error:'SyntaxError: Malformed token, expected \'\]\' after "Str"',
                    ']':{
                        token:'Str[]',
                        def:{
                            res:true,
                            typeof:true,
                            Str:true,
                            String:true,
                            List:true
                        }
                    }
                },
                '(':{
                    error:'SyntaxError: Malformed token, expected \'\)\' after "Str"',
                    ')':{
                        token:'Str()',
                        def:{
                            res:true,
                            typeof:true,
                            Str:true,
                            String:true,
                            Call:true
                        }
                    }
                }
            }
        }
    },
    t:{
        token:'t',
        def:{
            char:true
        },
        r:{
            token:'tr',
            def:{
                char:true
            },
            u:{
                token:'tru',
                def:{
                    char:true
                },
                e:{
                    token:'true',
                    def:{
                        res:true,
                        value:true,
                        bool:true,
                        true:true
                    }
                }
            }
        },
        y:{
            token:'ty',
            def:{
                char:true
            },
            p:{
                token:'typ',
                def:{
                    char:true
                },
                e:{
                    token:'type',
                    def:{
                        res:true,
                        type:true,
                        assign:true,
                        newType:true
                    }
                }
            }
        }
    },
    v:{
        token:'v',
        def:{
            char:true
        },
        o:{
            token:'vo',
            def:{
                char:true
            },
            i:{
                token:'voi',
                def:{
                    char:true
                },
                d: {
                    token:'void',
                    def:{
                        res:true,
                        type:true,
                        assign:true,
                        void:true
                    }
                }
            }
        }
    },
    w:{
        token:'w',
        def:{
            char:true
        },
        h:{
            token:'wh',
            def:{
                char:true
            },
            i:{
                token:'whi',
                def:{
                    char:true
                },
                l:{
                    token:'whil',
                    def:{
                        char:true
                    },
                    e: {
                        token:'while',
                        def:{
                            res:true,
                            statement:true,
                            scope:true,
                            while:true
                        }
                    }
                }
            }
        }
    }
};